=== eduardocesar93/FGV-Goal/question.dtd
<!ENTITY % URI "CDATA" > 

<!ELEMENT question (text,explanation,choice+) >
<!ATTLIST question
	  level   CDATA #REQUIRED
	  chapter CDATA #REQUIRED
	  id      CDATA #REQUIRED >

<!-- como fazer para aceitar qualquer tag aceita dentro de div (html:
  p, listas, tabela, quote) menos campos de formularios e formularios?
  talvez redeclarar apenas o que queremos? img, ul, li, ol, a etc -->

<!ELEMENT text (#PCDATA|img|a|b|i|code|ul|ol|p)* >
<!ELEMENT explanation (#PCDATA|img|a|b|i|code|ul|ol|p)* >

<!ELEMENT choice (text,explanation) >
<!ATTLIST choice
	  type (correct|incorrect) "correct" >

<!ELEMENT a (#PCDATA) >
<!ATTLIST a
	  src %URI; #REQUIRED >

<!ELEMENT ul (#PCDATA|li) >
<!ATTLIST ul
	  style %URI; #REQUIRED >

<!ELEMENT ol (#PCDATA|li) >
<!ATTLIST ol
	  style %URI; #REQUIRED >

<!ELEMENT code (#PCDATA) >
<!ATTLIST code
	  lang %URI; #REQUIRED >

<!ELEMENT img (#PCDATA) >
<!ATTLIST img
	  href %URI; #REQUIRED 
	  target CDATA #REQUIRED >

<!ELEMENT b (#PCDATA) >
<!ELEMENT i (#PCDATA) >

<!ELEMENT p (#PCDATA) >
<!ELEMENT li (#PCDATA) >

=== eduardocesar93/FGV-Goal/questions/template-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE question SYSTEM "question.dtd">

<question id="1" level="1" subject="calculus">
  <text>
    Calcule a seguinte integral $\int \cos \theta \,d\theta$
  </text>
  <explanation>
    <i>Explicação da questão</i>
  </explanation>
  <choice type="correct">
    <text><b>opção 1</b></text>
    <explanation>
      Utilizando o método de integral tal <a href="https://www.google.com.br/search?q=parsexml+error+in+url&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=yb-kV-3RDfOp8wfVnS8#q=parse+xml+error+in+url+jquery" target="_blank">informações adicionais</a>
    </explanation>
  </choice>
  <choice type="incorrect">
    <text>opção 2</text>
    <explanation>
      Utilizando ...
    </explanation>
  </choice>
  <choice type="incorrect">
    <text>opção 3</text>
    <explanation>
      Utilizando ...
    </explanation>
  </choice>
  <choice type="incorrect">
    <text>opção 4</text>
    <explanation>
      Utilizando ...
    </explanation>
	</choice>
	<choice type="incorrect">
		<text>opção 5</text>
		<explanation>
			Utilizando ...
		</explanation>
	</choice>
	<choice type="incorrect">
		<text>opção 6</text>
	</choice>
	<choice type="correct">
		<text>opção 7</text>
		<explanation>
			<img src="http://www.clickgratis.com.br/fotos-imagens/imagem/aHR0cHM6Ly9lbmNyeXB0ZWQtdGJuMi5nc3RhdGljLmNvbS9pbWFnZXM/cT10Ym46QU5kOUdjU1ZFbkFCS0szMktsZmhDN2NjSmxYTXVISWN2QzZWdEZXdW9wMy1QMEhJNjVxSUlBaFRvZw==.jpg" />
		</explanation>
	</choice>
	<choice type="incorrect">
	  <text>opção 8</text>
	  <explanation>
	    qualquer
	  </explanation>
	</choice>
</question>

=== eduardocesar93/FGV-Goal/questions/template-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE question SYSTEM "question.dtd">

<question id="1" level="0" subject="graphs">
  <text>o texto da questão.</text>
  <explanation>a explicação.</explanation>
  <choice type="correct">
    <text>primeira possivel resposta</text>
    <explanation>explicacao da resposta</explanation>
  </choice>
  <choice type="incorrect">
    <text>segunda possivel resposta</text>
    <explanation>segunda explicacao da resposta</explanation>
  </choice>
</question>
